### ISSUE TITLE
Дозволити ходи лише на сусідні клітинки

### ISSUE THREAD

**Issue by g-old-en-eagle** [QuarantineGameTeam/team_5_game#16]

**Comment by grescher** [comment]
При спробі походити через клітинку в термінал поїхали алярми
```
2020/06/06 12:02:28 http: panic serving [::1]:64289: runtime error: index out of range [0] with length 0
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000144000)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x13dd8e0, 0xc0004051a0)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
team_5_game/service.ProcessWebhookMessage(0xc000365940)
	/Users/kas/go/src/team_5_game/service/message_service.go:37 +0x389
team_5_game/service.webhookHandler(0x1491340, 0xc00035f180, 0xc00014a200)
	/Users/kas/go/src/team_5_game/service/http_service.go:25 +0x187
net/http.HandlerFunc.ServeHTTP(0x142b640, 0x1491340, 0xc00035f180, 0xc00014a200)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0x1720640, 0x1491340, 0xc00035f180, 0xc00014a200)
	/usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000120000, 0x1491340, 0xc00035f180, 0xc00014a200)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000144000, 0x1491b00, 0xc0001360c0)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
```
